config/routes.rb
Rails.application.routes.draw do
  # get 'user/show/:id', to: 'user#show', as:'user'
  resources :user
  resources :city
  resources :gossip do
  resources :comment, only: [:index,:create] 
  end
  resources :root
  resources :contact
  resources :team
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, :content, presence: true 
  validates :title, length: { minimum: 3 }
end

app/models/gossip_tag_join.rb
class GossipTagJoin < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossiptagjoins
  has_many :gossips, through: :gossiptagjoins 
end 

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips
  has_many :comments
  belongs_to :city

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def show
    @city = City.find(params[:id])
    @users = City.find(params[:id]).users
    # @gossips = @users.gossips
  end

end

app/controllers/comment_controller.rb
class CommentController < ApplicationController

  def create
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new(content:params[:content], user_id = User.all.sample.id, :gossip_id: @gossip.id)

    if @comment.save
      redirect_to @gossip
    else
      render 'gossip/show'
    end
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def show
    @gossip =  Gossip.find(params[:id])
    @c_id = @gossip.user.city.id
    @u_id = @gossip.user.id
    @comments = Gossip.find(params[:id]).comments
    @comment = @gossip.comments.new
  end

  before_action :authenticate_user, only: [:index]
  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.create(title: params[:title], content: params[:content])
    @gossip.user = User.find_by(id: session[:user_id])
    if @gossip.save # essaie de sauvegarder en base @gossip
      flash[:success] = "Potin bien créé !"
      redirect_to root_index_path
    else
    # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      render 'new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id]) 
  end

  def update
    @gossip = Gossip.find(params[:id]) 

    if @gossip.update(title: params[:title], content: params[:content]) # essaie de sauvegarder en base @gossip
      redirect_to gossip_path
    else
      flash[:danger] = "Une erreur est survenue."
      render 'edit'
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id]) 

    if @gossip.destroy
      redirect_to root_index_path
    else
      render 'gossip'
    end
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  	@gossips = Gossip.all
  	puts "@" * 60
  	@first_name = params[:first_name]
  	puts "@" * 60
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(last_name: params[:last_name], first_name: params[:first_name], age: params[:age], email: params[:email], password: params[:password], password_confirmation: params[:password_confirmation], city: City.last) # avec xxx qui sont les données obtenues à partir du formulaire

    if @user.save # essaie de sauvegarder en base @gossip
      redirect_to root_index_path
    else
    # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @id = @user.city.id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/city/show.html.erb
<div class="container">
  <h2 class="card-title font-weight-bold"><%= @city.name %></h2>
  <% @users.each do |u| %>
    <% u.gossips.each do |g| %>
			<div class="col-md-3">
  			<div class="card mb-3" style="width: 18rem;">
	  			<div class="card-body">
            <h5 class="card-title"><a href="<%= gossip_path(g.id) %>"><%= g.title %></a></h5>
          </div>
          <div class="card-footer"><%= u.first_name %></div>
  			</div>
      </div>
      <%end%>
  	<%end%>
  </div>

app/views/gossip/edit.html.erb
  <div class="container">
    <%= form_for @gossip, url: {action: "update"} do |f| %>
    <%= f.text_field :title %>
    <br><br>
    <%= f.text_area :content %>
    <br><br>
    <%= f.submit "Edit Gossip" %>
    <% end %>
  </div>

app/views/gossip/new.html.erb
  <div class="container">
      <%= form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', @gossip.title %>
      <br /> <br />

      <%= label_tag 'Content' %>
      <%= text_area_tag 'content', @gossip.content %>
      <br /> <br />

      <%= submit_tag "Create Gossip" %>

    <% end %>
  </div>

app/views/gossip/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Gossip <%= @gossip.id%></title>
</head>
<body>
  <div class="container">
    <div class="card ">
	  <div class="card-header bg-primary text-white">
	      <h3><%= @gossip.title %></h3>
	    </div>
	    <div class="card-body">
	      <blockquote class="blockquote mb-0">
	      <p><%= @gossip.content %></p>
	      <footer class="blockquote-footer"><cite title="Source Title"><%= @gossip.user.first_name%> <%= @gossip.user.last_name%> from <a href="<%= city_path(@c_id) %>"><%= @gossip.user.city.name%></a></cite> <a href="<%= user_path(@u_id)%>">(Afficher le profil de l'auteur)</a></footer>
	      </blockquote>
	    </div>
	    <div class="card-footer small">Posté le <%= @gossip.created_at.strftime('%d-%m-%Y') %></div>
		</div>
		<div class="d-flex mt-3 mb-4">
			<% if current_user.id == @gossip.user.id%>
			<p>
		 		<button class="btn btn-secondary"><a href="<%= edit_gossip_path %>" class="text-white">Editer le gossip</a></button>
			</p>
			<p>
				<button class="btn btn-danger ml-2"><a href="<%= gossip_path %>" class="text-white" data-confirm="Etes-vous sur ?" data-method="DELETE">Supprimer le gossip</a></button>
			</p>
			<% else %>
			<% end %>
		</div>

<!-- comment block -->
			<h3 class="mt-3 mb-3">Commentaires</h3>
			<% @comments.each do |c| %>
				<div class="col-md-8">
  				<div class="card mb-3" style="width: 48rem;">
	  				<div class="card-body">
        			<h5 class="card-title"><%= c.content %></a></h5>
  					</div>
  	  			<div class="card-footer"><%= c.user.first_name %></div>
  				</div>
				</div>
  		<%end%>
  </div>
</body>
</html>

app/views/user/new.html.erb
<div class="container">
  <%= form_tag url_for(action: 'create'), method: "post" do %>

  <%= label_tag 'Nom' %>
  <%= text_field_tag 'last_name', @user.last_name %>
  <br /> <br />

  <%= label_tag 'Prenom' %>
  <%= text_field_tag 'first_name', @user.first_name %>
  <br /> <br />

  <%= label_tag 'Age' %>
  <%= text_field_tag 'age', @user.age %>
  <br /> <br />

  <%= label_tag 'Email' %>
  <%= text_field_tag 'email', @user.email %>
  <br /> <br />

  <%= label_tag 'Mot de passe' %>
  <%= password_field_tag 'password', @user.password %>
  <br /> <br />

  <%= label_tag 'Confirmer votre mot de passe' %>
  <%= password_field_tag 'password_confirmation', @user.password_confirmation %>
  <br /> <br />
  
  <%= submit_tag "Sign up" %>

<% end %>
</div>

app/views/user/show.html.erb
<div class="container">

  <div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="" class="card-img" alt="">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title font-weight-bold"><%= @user.last_name %> <%= @user.first_name %></h5>
          <p class="card-text"><span class="text-primary">Age :</span> <%= @user.age %> ans</p>
      	  <p class="card-text"><span class="text-primary">Email :</span> <%= @user.email %></p>
          <p class="card-text"><span class="text-primary">Ville :</span> <a href="<%= city_path(@id) %>"> <%= @user.city.name %></a></p>
          <p class="card-text"><span class="text-primary">Description :</span> <%= @user.description %></p>
          <p class="card-text"><small class="text-muted">Last updated <%= @user.updated_at.strftime('%d-%m-%Y') %></small></p>
      </div>
    </div>
  </div>
    <button class="btn btn-secondary"><a class="text-white" href="<%= gossip_path %>">Revenir au Gossip</a></button>
</div>
</div>