config/routes.rb
Rails.application.routes.draw do
  # get 'user/show/:id', to: 'user#show', as:'user'
  resources :user
  resources :city
  resources :gossip do
  resources :comment, only: [:index,:create] 
  end
  resources :root
  resources :contact
  resources :team
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, :content, presence: true 
  validates :title, length: { minimum: 3 }
end

app/models/gossip_tag_join.rb
class GossipTagJoin < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossiptagjoins
  has_many :gossips, through: :gossiptagjoins 
end 

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips
  has_many :comments
  belongs_to :city

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def show
    @city = City.find(params[:id])
    @users = City.find(params[:id]).users
    # @gossips = @users.gossips
  end

end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  	@gossips = Gossip.all
  	puts "@" * 60
  	@first_name = params[:first_name]
  	puts "@" * 60
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js">
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <header class="mb-4">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">The Gossip Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="<%= root_index_path %>">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= team_index_path %>">Team</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= contact_index_path %>">Contact</a>
            </li>
          </ul>
          <ul class="navbar-nav my-2 my-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_path %>">Sign up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_session_path %>">Login</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>